apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: git@github.com:1DCLT-TECH-CHALLENGE/togglemaster-tc.git
    targetRevision: main
    path: fase4/gitops/observability/namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
