apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-opentelemetry-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.156.2
      helm:
        releaseName: opentelemetry-collector
        valueFiles:
          - $values/fase4/gitops/observability/values/opentelemetry-collector-values.yaml
    - repoURL: git@github.com:1DCLT-TECH-CHALLENGE/togglemaster-tc.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
