apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: 6.17.1
      helm:
        releaseName: promtail
        valueFiles:
          - $values/fase4/gitops/observability/values/promtail-values.yaml
    - repoURL: git@github.com:1DCLT-TECH-CHALLENGE/togglemaster-tc.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
