apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: togglemaster-observability
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
    - port: prometheus
      path: /metrics
      interval: 30s
