apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: dev

replicas:
  - name: auth-service
    count: 2
  - name: flag-service
    count: 2
  - name: targeting-service
    count: 2
  - name: evaluation-service
    count: 2
  - name: analytics-service
    count: 1
